# Generated by Django 2.2.28 on 2022-07-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0002_clue_entry_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='entry',
        ),
        migrations.AddField(
            model_name='clue',
            name='entry',
            field=models.ManyToManyField(related_name='clues', to='xword_data.Entry'),
        ),
    ]
